alias update='sudo apt-get update && sudo apt-get upgrade'
alias top='htop'
alias ls='ls -F --col'
alias ll='ls -l'
alias s='cd ..'
alias packup='/bin/tar -czvf'
alias diskspace='df -h | grep -E "(Filesystem|\/dev\/simfs)"'
alias largest='find . -type f -print0 | xargs -0 du -s | sort -n | tail -10 | cut -f2 | xargs -I{} du -sh {}'
alias unpack='/bin/tar -xzvpf'
alias contents='/bin/tar -tzf'
alias mktd='tdir=`mktemp -d` && cd $tdir'
alias proc='ps aux | grep'
alias ex='unp'
